// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testg/user_vo.proto

/*
Package testg is a generated protocol buffer package.

It is generated from these files:
	testg/user_vo.proto
	testg/user_server.proto

It has these top-level messages:
	Empty
	UserList
	User
	Msg
*/
package testg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UserList struct {
	U []*User `protobuf:"bytes,1,rep,name=u" json:"u,omitempty"`
}

func (m *UserList) Reset()                    { *m = UserList{} }
func (m *UserList) String() string            { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()               {}
func (*UserList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserList) GetU() []*User {
	if m != nil {
		return m.U
	}
	return nil
}

type User struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Age      int32  `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
	Msg      *Msg   `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetMsg() *Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Msg struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Msg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "testg.Empty")
	proto.RegisterType((*UserList)(nil), "testg.UserList")
	proto.RegisterType((*User)(nil), "testg.User")
	proto.RegisterType((*Msg)(nil), "testg.Msg")
}

func init() { proto.RegisterFile("testg/user_vo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8f, 0x4f, 0x8b, 0xc2, 0x30,
	0x10, 0xc5, 0xc9, 0xa6, 0x7f, 0xa7, 0x97, 0x25, 0x7b, 0x68, 0x96, 0xdd, 0x43, 0x08, 0x08, 0x39,
	0x55, 0xa8, 0x9f, 0xc1, 0x83, 0x60, 0x3d, 0x04, 0x3c, 0x4b, 0xa5, 0x21, 0x14, 0x8c, 0x2d, 0x4d,
	0x2a, 0xf8, 0xed, 0x65, 0xa2, 0xb7, 0x37, 0xef, 0xf7, 0x66, 0x1e, 0x03, 0x3f, 0xc1, 0xf8, 0x60,
	0xb7, 0xab, 0x37, 0xcb, 0xe5, 0x31, 0x35, 0xf3, 0x32, 0x85, 0x89, 0xa5, 0xd1, 0x94, 0x39, 0xa4,
	0x7b, 0x37, 0x87, 0xa7, 0xdc, 0x40, 0x71, 0xf6, 0x66, 0x39, 0x8e, 0x3e, 0xb0, 0x5f, 0x20, 0x2b,
	0x27, 0x82, 0xaa, 0xaa, 0xad, 0x9a, 0x98, 0x6b, 0x90, 0x69, 0xb2, 0xca, 0x1b, 0x24, 0x28, 0x59,
	0x0d, 0x79, 0xbc, 0x37, 0x0e, 0x9c, 0x08, 0xa2, 0x4a, 0x9d, 0xe1, 0x78, 0x18, 0xd8, 0x1f, 0x94,
	0x11, 0xdc, 0x7b, 0x67, 0xf8, 0x57, 0x44, 0x05, 0x1a, 0xa7, 0xde, 0x19, 0xf6, 0x0d, 0xb4, 0xb7,
	0x86, 0x53, 0x41, 0x54, 0xaa, 0x51, 0xb2, 0x7f, 0xa0, 0xce, 0x5b, 0x9e, 0x08, 0xa2, 0xaa, 0x16,
	0x3e, 0x65, 0x9d, 0xb7, 0x1a, 0x6d, 0x59, 0x03, 0xed, 0xbc, 0xc5, 0x35, 0x0c, 0xbd, 0x8b, 0x50,
	0x5e, 0xb3, 0xf8, 0xc4, 0xee, 0x15, 0x00, 0x00, 0xff, 0xff, 0x31, 0xda, 0xbf, 0x2c, 0xdb, 0x00,
	0x00, 0x00,
}
